### ISSUE TITLE
[utilisateurs] certains utilisateurs sont dans la base mais pas dans sendinblue

### ISSUE THREAD

**Issue by annepoirot** [betagouv/recosante-api#175]

**Comment by l-vincent-l** [comment]
* Début d’investigation : 

En faisant la différence entre les utilisateurs que l’on a en base et ceux que l’on a en dans sendinblue je trouve, j’ai 90 inscriptions concernées.

Parmis celles-ci il y 8 inscriptions commençant par `test` que je peux supprimer sans trop réfléchir.
