### ISSUE TITLE
[QA] ATMO Auvergne Rhone Alpes fonctionne avec des bassin d'air

### ISSUE THREAD

**Issue by annepoirot** [betagouv/recosante-api#182]
On ne peut pas mettre que l'épisode de pollution est sur le département, on peut mettre sur la ville.

**Comment by florianpanchout** [comment]
@annepoirot C'est à dire ? C'est une modification à apporter seulement pour la région Auvergne Rhone Alpes ? 
Est ce qu'il faut que la localisation de l'épisode de pollution soit une propriété Sendinblue ?

**Comment by annepoirot** [comment]
C'était une question de wording si ne me trompe pas. En gros on pouvait pas dire pour la région Auvergne Rhone Alpes qu'il y avait un épisode de pollution "dans votre département" car les données d'épisode de pollution ne sont pas mesurées/partagées au niveau du département dans cette région (comme c'est le cas ailleurs) mais au niveau des bassin d'air... Donc la reco de ATMO était de mettre dans ce cas "dans votre ville"

**Comment by florianpanchout** [comment]
@annepoirot 

Est ce que ce ne serait pas l'occasion de mettre la phrase 

> Un épisode de pollution {{contact.POLLUANT}} est prévu aujourd'hui dans votre département.

entièrement en base ? Comme ça on peut réutiliser ce cadre pour toutes les autres alertes (canicule, grand froid, etc...)
