### ISSUE TITLE
[recos] les recommandations sur le chauffage ne sont pas personnalisées

### ISSUE THREAD

**Issue by annepoirot** [betagouv/recosante-api#197]
- Lier les recommandations chauffage au bois avec le questionnaire.
- Lier la recommandation "Tous les ans, avant l’hiver, faire vérifier son système de chauffage par un·e professionel·le qualifié·e." avec les personnes ayant répondu "chaudière"
- Lier la recommandation "Il est déconseillé d'utiliser un chauffage mobile d'appoint (radiateur électrique, bain d'huile ou au gaz) en continu." avec les personnes ayant répondu "chauffage d'appoint" 

=> Une personne peut avoir des système de chauffage différent => ne pas rendre la selection des recos exclusive

**Comment by l-vincent-l** [comment]
Fixé par https://github.com/betagouv/recosante-api/commit/b8b4adfd533e60b2e0c0cc5e8c128783e5e84f24
