### ISSUE TITLE
[données d'outre mer] mettre un message d'erreur lorsque les personnes s'inscrivent pour Mayotte, Guyane, Réunion, Nouvelle Calédonie.

### ISSUE THREAD

**Issue by annepoirot** [betagouv/recosante-api#203]
Message pour les personnes s'inscrivant dans les régions suivantes:
- Polynésie française
- Saint Martin
- La réunion
- Nouvelle calédonie

Le message : 
Malheureusement, nous ne pouvons pas vous envoyer la lettre d'information Recosanté. Les données de l'indice de qualité de l'air ne sont pas disponibles dans votre région.

**Comment by l-vincent-l** [comment]
J’ai ajouté un point d’entrée `/city-availability`
