### ISSUE TITLE
Ajouter objectifs dans recos

### ISSUE THREAD

**Issue by annepoirot** [betagouv/recosante-api#219]
à ajouter : 
- limiter les effets de la pollution de l'air sur votre santé

(pour les épisodes de pollution)

**Comment by annepoirot** [comment]
Est-ce que c'est possible aussi de les mettre tout en minuscule pour qu'elles puissent s'intégrer à la phrase d'intro du template ?

**Comment by l-vincent-l** [comment]
C’est fait
