### ISSUE TITLE
[page stats] Ajouter les nouvelles données

### ISSUE THREAD

**Issue by annepoirot** [betagouv/recosante-api#230]
- nombre de prescripteurs
    - association
    - CHU
    - médias
    - ...
- nombre d'intégration du widget

**Comment by florianpanchout** [comment]
@annepoirot 

La ligne "..." n'est pas très clair aha

Tu veux afficher quoi comme donnée en plus, et quels sont les chiffres que je mets pour l'instant ?

**Comment by annepoirot** [comment]
On a travaillé sur une proposition avec Marine pour la page stat dans son ensemble :https://pad.incubateur.net/q0CxL_xVRm6QyDnjNudgDA

On peut se prendre 30 minutes semaine pro pour en discuter @florianpanchout 

Pour la partie acquisition, pour le moment on a pas les chiffres exacts car le CRM s'est mal importé, j'essaye d'avoir ça semaine prochaine aussi.

**Comment by MarinePurson** [comment]
@florianpanchout ta proposition me convient à ce stade !

**Comment by annepoirot** [comment]
Évolution du nombre d'abonnés à la lettre d'information => je dirais par semaine 

Taux d'ouverture de la lettre d'information quotidienne => oui je pense qu'il faut afficher la veille parce que sinon on va avoir des chiffre très bas. 

Taux d'ouverture de la lettre d'information hebdomadaire => ok pour l'avant dernière aussi

Évolution du nombre de visiteurs du widget => par semaine du coup

**Comment by florianpanchout** [comment]
Nouvelle proposition de page stats avec la nouvelle version du service : 

### Indicateurs
- Total du nombre d'abonnés aux indicateurs
- Évolution du nombre d'abonnés aux indicateurs (par semaine)
- Pourcentage d'abonnés qui ont souscris à chacun des jeux de donnée
- Répartition par fréquence
- Répartition par média

### Lettre d'information
- Total du nombre d'abonnés à la lettre d'information
- Évolution du nombre d'abonnés à la lettre d'information (par semaine)
- Évolution des abonnements et des désabonnements (par semaine)
- Temps moyen d'abonnement d'un utilisateur
- Taux d'ouverture de la lettre d'information 
- Répartition des réponses à la question "Allez-vous appliquer cette recommandation ?"

### Dashboard
- Total du nombre de visiteurs du dashboard
- Évolution du nombre de visiteurs du dashboard (par semaine)
- Pourcentage des visiteurs via iframe

### Bizdev
- Nombre de prescripteurs de Recosanté
    - Professionnels de santé (CHU, fédération, société savante, syndicat, unions régionales)
    - Associations de patients
    - Associations et fédérations sportives

**Comment by MarinePurson** [comment]
Ca me va ! 

- Pour la lettre d'information, je préciserais "hebdomadaire" pour qu'on sache bien de quoi on parle.
- Pour la partie Bizdev, difficile maintenant de distinguer ces 3 cibles, ça me semblerait plus simple de mettre "nombre de prescripteurs" dans un premier temps et d'enrichir à l'avenir

**Comment by annepoirot** [comment]
A faire : 
- [ ] Valider les donnés qu'on veut afficher (car ça date de début novembre)
- [ ] Avoir les données côté API
- [ ] Faire le front

**Comment by MarinePurson** [comment]
Quelques interrogations : 
1. Peut-être ajouter le nombre d'intégrations de widgets ?

2. Je trouve que distinguer "indicateurs" et "lettre d'info" est intéressant si on parle de la lettre d'info hebdo, mais du coup ces stats renvoient plutôt au mail d'indicateurs : 
Lettre d'information
- Évolution des abonnements et des désabonnements (par semaine)
- Temps moyen d'abonnement d'un utilisateur
- Taux d'ouverture de la lettre d'information
- Répartition des réponses à la question "Allez-vous appliquer cette recommandation ?"

3. Pour la partie Bizdev, je me demande si c'est utile en fait... Ou alors par cible : médecins / collectivités... Qu'en pensez-vous ?

**Comment by florianpanchout** [comment]
On pourrait simplifier effectivement en considérant les abonnés à la newsletter hebdomadaire comme un sous-ensemble des abonnés aux indicateurs.

Ça donnerait quelque chose comme : 

### Abonnés
- Total du nombre d'abonnés aux indicateurs
- Évolution du nombre d'abonnés aux indicateurs (par semaine)
- Pourcentage d'abonnés qui ont souscris à chacun des jeux de donnée
- Répartition par fréquence
- Répartition par média
- Pourcentage abonnés à la lettre d'information hebdomadaire
- Taux d'ouverture de la lettre d'information hebdomadaire
- Répartition des réponses à la question " Ces contenus vous on-t-il été utiles ?"

### Dashboard
- Total du nombre de visiteurs du dashboard
- Évolution du nombre de visiteurs du dashboard (par semaine)
- Pourcentage des visiteurs via iframe

**Comment by MarinePurson** [comment]
Ca me va ! 
Concernant le nombre de widgets, ça vous semble pas intéressant ?

**Comment by fcoufour** [comment]
Au final, 3 sous-parties :

### Statistiques du site web (tableau de bord)

- nombre total de visites
- évolution du nombre de visites mensuelles
- évolution du nombre de visites mensuelles sur le tableau de bord
- répartition du % de visites entre widget et site web
- répartition du % de visites selon les canaux (moteur de recherche, visites directes, autres canaux)

### Statistiques de l'abonnement par email (aux indicateurs)
- nombre d'utilisateurs actuellement abonnés
- évolution du nombre d'abonnés par mois
- % d'abonnés à l'Indice ATMO de la qualité de l'air
- % d'abonnés au Risque d’allergie aux pollens
- % d'abonnés à la Vigilance météo
- % d'abonnés à l'Indice UV
- répartition du % d'abonnés entre la réception quotidienne et la réception en cas de vigilance
- répartition du % d'abonnés entre la réception par email et pas notification web
- évolution du taux de désinscription par mois
- durée moyenne d'inscription (pour les abonnés actuels, le temps considéré est la différence entre aujourd'hui et la date d'inscription)

### Statistiques de l'abonnement à l'infolettre
- nombre d'abonnés à la lettre d'information hebdomadaire
- taux d'ouverture global pour tous les sujets
- % d'abonnés satisfaits du contenu des newsletters (suite à l'enquête de satisfaction en bas de chaque infolettre)

PR côté frontend : https://github.com/betagouv/recosante/pull/200
PR côté API : https://github.com/betagouv/recosante-api/pull/382

**Comment by fcoufour** [comment]
@annepoirot @MarinePurson La nouvelle page https://recosanteprod-newstats.gtsb.io/stats/, l'actuelle  https://recosante.beta.gouv.fr/stats/. Je vous laisse regarder cette semaine pour me dire si qqch vous manque ou non. J'ai sous le coude des taux d'ouverture par sujet de newsletter si ça vous intéresse.

**Comment by MarinePurson** [comment]
Ca me va, merci beaucoup ! 

Alors les taux d'ouverture par sujet de newsletter, pas forcément pour la page stats mais si on peut intégrer ça au tableau de suivi des newsletters, c'est top ! Depuis peu, je suis le nombre de désinscrits par sujet : https://docs.google.com/spreadsheets/d/1wFHFL0EMfjXtXFDHYzMdqTkehbPcTpM3ALJYH_Uwx1c/edit#gid=1918659743

**Comment by fcoufour** [comment]
Tout à fait, c'est ce qui m'a donné l'idée d'ajouter ça à l'API. Les taux de la la salve précédente sont disponibles ici : https://api.recosante.beta.gouv.fr/stats/email/openings. Avec les différences vs le taux SIB que j'évoquais sur Mattermost

**Comment by fcoufour** [comment]
Sinon, pour la page en tant que telle, je laisse quelques jours en parallèle pour voir si qqch vous manque ou je mets en ligne ?

**Comment by MarinePurson** [comment]
Pour moi c'est ok, je laisse @annepoirot confirmer

**Comment by annepoirot** [comment]
Ca me convient aussi !
