### ISSUE TITLE
[NL] modifier la phrase d'introduction pour qu'elle soit entièrement dans la base

### ISSUE THREAD

**Issue by annepoirot** [betagouv/recosante-api#235]
- Anne fait une liste des phrases

**Comment by florianpanchout** [comment]
@l-vincent-l Est ce qu'on ne peut pas juste automatiser l'ajout de "Aujourd’hui, votre recommandation est un conseil pratique pour " au début de chaque intro ?

**Comment by annepoirot** [comment]
Reprendre les objectifs qui sont dans le catalogue de recommandations. Au lieu d'avoir le début de phrase fixe "Aujourd’hui, votre recommandation est un conseil pratique..." et les objectifs ensuite, ajouter en base l'ensemble de la phrase. 
Le début sera différent pour les recommandations radon, d'où la nécessité de mettre la phrase en entier dans la base.

**Comment by l-vincent-l** [comment]
@florianpanchout Je pense qu’il y a des modifications à apporter au mail du coup

**Comment by florianpanchout** [comment]
Template modifié pour ne plus avoir "Aujourd’hui, votre recommandation est un conseil pratique " en dur

**Comment by florianpanchout** [comment]
@l-vincent-l il manque la virgule après "Aujourd’hui"

**Comment by annepoirot** [comment]
[Urgent] il y a une coquille dans la phrase d'introduction, on a 3 "m" à "recommandation" ! Est-ce que tu peux modifier ça aujourd'hui @florianpanchout ? Sinon je crois que je sais comment faire !

**Comment by florianpanchout** [comment]
Ahahahaha comment j'ai raté ça.
Je vois le fichier où changer ça mais pas sur de savoir mettre en prod. Perso j'attendrais le retour de Vincent
