### ISSUE TITLE
Envoi la newsletter à midi si pas de données

### ISSUE THREAD

**Issue by l-vincent-l** [betagouv/recosante-api#236]
Reste à déterminer :
 - qu’affiche t-on en cas d’absence de donnée ? Indique t-on l’absence ? Ou bien le cadre est-il caché ?

**Comment by florianpanchout** [comment]
Le cadre avec un message "données indisponibles aujourd'hui. Rendez vous sur [site de l'ASQUAA] pour les voir." C'est ce qui me semble le plus propre non ?

Je devrais pouvoir conditionner l'affichage de ce message selon que la propriété Sendinblue est vide ou non (pour l'instant je cache le cadre)

**Comment by l-vincent-l** [comment]
Je suppose que la newsletter ne s’envoie que si au moins un des arguments `SHOW_*` est vrai

**Comment by florianpanchout** [comment]
Ça fonctionne comment maintenant ? Tentative d'envoi tous les 1/4 d'heure puis envoi sans l'indicateur à midi ?

Et maintenant dans le template je me base sur la présence ou non de QUALITE_AIR pour 
-  afficher l'indicateur si QUALITE_AIR est rempli
- afficher un message d'erreur s'il est null
?

(Ps: est ce que ça te va de ne pas close les issues mais de plutôt les réassigner à Anne ou moi ?)

**Comment by l-vincent-l** [comment]
> Ça fonctionne comment maintenant ? Tentative d'envoi tous les 1/4 d'heure puis envoi sans l'indicateur à midi ?
Oui c’est ça

> Et maintenant dans le template je me base sur la présence ou non de QUALITE_AIR pour
> 
>     * afficher l'indicateur si QUALITE_AIR est rempli
> 
>     * afficher un message d'erreur s'il est null

Yep tu peux faire comme ça
>       ?
> 
> 
> (Ps: est ce que ça te va de ne pas close les issues mais de plutôt les réassigner à Anne ou moi ?)

Très bien !

**Comment by florianpanchout** [comment]
J'affiche maintenant

> L'indice de qualité de l'air à {{contact.VILLE}} n'est pas disponible au moment de l'envoi de cet email.
[Retrouvez-le ici.]

lorsque QUALITE_AIR n'est pas défini
