### ISSUE TITLE
Utiliser une url recosante pour l'api

### ISSUE THREAD

**Issue by florianpanchout** [betagouv/recosante-api#239]
Passer de https://ecosante.beta.gouv.fr/data à

- https://recosante.beta.gouv.fr/data 

ou

- https://api.recosante.beta.gouv.fr (mon pref)

**Comment by annepoirot** [comment]
Moi je préfères aussi https://api.recosante.beta.gouv.fr

**Comment by l-vincent-l** [comment]
J’ai créé le domaine api.recosante.beta.gouv.fr
Le petit défaut de naming c’est que ça pointe aussi sur l’admin

**Comment by florianpanchout** [comment]
Ça pointe sur l'admin, c'est à dire ?

**Comment by florianpanchout** [comment]
Hello @l-vincent-l,

Qu'est ce que tu entends par "ça pointe aussi sur l’admin" ?
