### ISSUE TITLE
Nommage des différents repo

### ISSUE THREAD

**Issue by florianpanchout** [betagouv/recosante-api#240]
@annepoirot @l-vincent-l Est ce que ce ne serait pas plus logique de faire quelque chose comme : 

betagouv/recosante-api => betagouv/recosante-mail (qui intégrerais aussi les templates de mail ?)

betagouv/indice_pollution => betagouv/recosante-api 

À voir selon les limitation de nommage de Github

**Comment by annepoirot** [comment]
Oui moi ça m'irait

**Comment by florianpanchout** [comment]
Décision de planif du 19/07 : création d'une nouvelle orga Recosanté
