### ISSUE TITLE
Des recommandations de mêmes catégories s'envoient deux jours d'affilés

### ISSUE THREAD

**Issue by annepoirot** [betagouv/recosante-api#242]
Dans mon cas, le 14/07 j'ai reçu :
Nettoyer le plus souvent possible sans produits chimiques, avec de la vapeur d'eau, des chiffons humides ou en microfibres.

Puis le 15/07 j'ai reçu : 
Nettoyer les sols de son logement avec un mélange à base d'eau plutôt qu'un balayage simple pour éviter la remise en suspension des poussières.

**Comment by annepoirot** [comment]
Le 14/07 : Nettoyer le plus souvent possible sans produits chimiques, avec de la vapeur d'eau, des chiffons humides ou en microfibres.
Le 15/07 : Nettoyer les sols de son logement avec un mélange à base d'eau plutôt qu'un balayage simple pour éviter la remise en suspension des poussières.

**Comment by l-vincent-l** [comment]
Dans le cas évoqué voici ce qu’il se passe.

Tu as reçu toutes les recommandations qui étaient dispo.
On refait une liste avec les recommandations qui sont éligibles pour toi ce jour ci (en regardant l’état de la qualité de l’air et ton profil).
Puis on les ordonne en fonction d’abord de la dernière date d’envoi, puis si elles n’ont pas été envoyées en fonction du nombre de critères différents par rapport à la dernière reco envoyé, puis s’il y a le même nombre, on regarde si le type de recommandation est différent.

Le point faible de cet algo c’est que si on a déjà envoyé toutes les recos, celle envoyée depuis le plus de temps est renvoyée.

On pourrait imaginer plusieurs choses, comme par exemple considérer que toutes les recommandations envoyées depuis plus de _x_ mois ne soient plus ordonnées entre elles pour comparer directement sur le nombre de critères en commun avec la dernière recommandation envoyée.

Je veux bien des retours là dessus, et peut être en parler parce que je peux imaginer que ce ne soit pas clair

**Comment by florianpanchout** [comment]
Ça me semble clair. Effectivement, ne plus prendre en compte le critère temps à partir d'un certain nombre de mois me parait être le plus judicieux. C'est couteux en temps ?
