### ISSUE TITLE
Uniformiser le format de retour de l'api

### ISSUE THREAD

**Issue by florianpanchout** [betagouv/recosante-api#243]
Actuellement le format est différent entre pollens, qa et radon.

**Comment by l-vincent-l** [comment]
tu parles de l’API disponible sur `/data` ?

**Comment by florianpanchout** [comment]
Yes. Proposition de format pour uniformiser l’ensemble :

`{
  "commune": {
    "code": "25056",
    "nom": "Besançon",
    "codesPostaux": ["25000"],
    "departement": {
      "code": "25",
      "nom": "Doubs"
    }
  },
  "indice_atmo": {
    "indice": {
      "value": 2,
      "label": "Dégradé",
      "color": "#50F0E6",
      "details": [
        {
          "label": "PM2.5",
          "indice": {
            "value": 2,
            "label": "Dégradé",
            "color": "#50F0E6"
          }
        },
        {
          "label": "PM10",
          "indice": {
            "value": 2,
            "label": "Dégradé",
            "color": "#50F0E6"
          }
        },
        {
          "label": "O3",
          "indice": {
            "value": 2,
            "label": "Dégradé",
            "color": "#50F0E6"
          }
        },
        {
          "label": "NO2",
          "indice": {
            "value": 2,
            "label": "Dégradé",
            "color": "#50F0E6"
          }
        },
        {
          "label": "SO2",
          "indice": {
            "value": 2,
            "label": "Dégradé",
            "color": "#50F0E6"
          }
        }
      ]
    },
    "advice": {
      "main": "Même lorsque la qualité de l'air est dégradé comme aujourd’hui, il est nécessaire d'aérer son logement pour faire circuler l'air.",
      "details": "ℹ️ Ouvrir les fenêtres au moins 10 minutes, de préférence tôt le matin et tard le soir, en dehors des heures de pointe. Les heures de pointe où les taux de pollution sont les plus élevés sont généralement entre 7h-10h et entre 17h-20h."
    },
    "validity": {
      "start": "2021-07-23T12:05:20.913Z",
      "end": "2021-07-23T12:05:20.913Z",
      "area": "Besançon"
    },
    "sources": [
      {
        "label": "ATMO Bourgogne-Franche-Comté",
        "url": "https://www.atmo-bfc.org/"
      }
    ]
  },
  "raep": {
    "indice": {
      "value": 2,
      "label": "Faible",
      "color": "#50F0E6",
      "details": [
        {
          "label": "Ambroisies",
          "indice": {
            "value": 2,
            "label": "Faible",
            "color": "#50F0E6"
          }
        },
        {
          "label": "Armoises",
          "indice": {
            "value": 2,
            "label": "Faible",
            "color": "#50F0E6"
          }
        },
        ...
      ]
    },
    "advice": {
      "main": "En cas de gêne répétitive et saisonnière liée aux symptômes ci-dessous, et dans un contexte de fatigue inhabituelle, vous souffrez peut être d’une allergie aux pollens. Prendre conseil auprès d’un professionnel.",
      "details": "ℹ️ Les symptômes en cas d’allergie aux pollens sont :<ul><li>crises d’éternuement ;</li><li>nez qui gratte, parfois bouché ou qui coule clair ;</li><li>yeux rouges, qui démangent ou qui larmoient ;</li><li>en association éventuelle avec une respiration sifflante ou une toux.</li></ul>💡L’allergie peut bénéficier de mesures de prévention et de soins. Pour cela demandez conseil à votre pharmacien ou consultez votre médecin."
    },
    "validity": {
      "start": "2021-07-23T12:05:20.913Z",
      "end": "2021-07-23T12:05:20.913Z",
      "area": "Doubs"
    },
    "sources": [
      {
        "label": "Le Réseau national de surveillance aérobiologique",
        "url": "https://www.pollens.fr/"
      },
      {
        "label": "Pollinarium Sentinelle",
        "url": "https://www.alertepollens.org/pages/pollinarium-sentinelle/"
      }
    ]
  },
  "potentiel_radon": {
    "indice": {
      "value": 2,
      "label": "Moyen",
      "color": "#50F0E6"
    },
    "advice": {
      "main": "Le radon est un gaz radioactif naturel présent dans le sol et les roches. Le potentiel radon fournit un niveau de risque relatif à l’échelle d’une commune. Il ne présage en rien des concentrations présentes dans votre habitation. Seul un mesurage vous permettra de savoir si du radon est présent dans votre habitation."
    },
    "validity": {
      "area": "Fontain"
    },
    "sources": [
      {
        "label": "L'institut de Radioprotection et de Sûreté Nucléaire",
        "url": "https://www.irsn.fr/"
      }
    ]
  }
}
`

(Tout est évidemment discutable, du format aux termes utilisés)

Je n’ai pas inclus épisode, n'ayant aucune compréhension de la chose pour l’instant.

Et questions : 

- Est ce que l’indice Atmo et le potentiel Radon commencent à 0 ou 1 ? Ça me semble logique que le raep commence à zéro (pour « Nul »). Mais ici j’ai peur que ça soit un contre sens de les faire commencer à zéro (pour « Bon » et « Faible »). @annepoirot un avis ?

- Est ce que c'est bien utile d'intégrer les couleurs ?

**Comment by l-vincent-l** [comment]
Le point d’entrée est ici http://ecosante.beta.gouv.fr/v1/?insee=75056

**Comment by florianpanchout** [comment]
Des premiers retours : 

- [ ] Il manque l'objet sources pour raep et radon
- [ ] Il manque l'objet validity pour radon
- [ ] Le label du raep n'a pas de majuscule
- [ ] Le radon n'a pas de label
- [ ] Il n'y a pas de recommandations pour le raep et le radon

**Comment by florianpanchout** [comment]
Le label de PM2,5 doit être "PM2,5" et pas "PM25". 
Et s'il est possible de les ordonner dans l'ordre d'affichage, ce serait plus propre

**Comment by l-vincent-l** [comment]
Tu veux ordonner de quelle manière ?

**Comment by l-vincent-l** [comment]
La validité des données pour le potentiel radon n’est pas précisé dans les données sources.
Je pense que c’est quelque chose qui ne bouge pas dans le temps

**Comment by florianpanchout** [comment]
Yes c'est juste pour le paramètre area :)

Pour les polluants c'est une bonne question !

J'affiche pour l'instant : PM2,5, PM10, NO2, 03, SO2. Mais je n'ai aucune idée d'ou je tire cet ordre... Je pensais que j'avais repris ça à AirPariff mais pas du tout. Chaque source que je trouve a un ordre différent...

@annepoirot @MarinePurson Un avis sur l'ordre des polluants ?

**Comment by MarinePurson** [comment]
Pas d'avis et pas de règle à ma connaissance

**Comment by florianpanchout** [comment]
@l-vincent-l Je ne trouve pas l'adresse pour le staging. https://staging.api.recosante.beta.gouv.fr/v1/?insee=75056 me renvoie une erreur ?

**Comment by florianpanchout** [comment]
Sinon sur http://ecosante.beta.gouv.fr/v1/?insee=25056 

- [ ] il manque validity pour le radon (avec juste area du coup)
- [ ] renommer les labels radons "Faible", "Moyen", "Élevé" pour correspondre aux maquettes
- [ ] enlever les points de "RNSA" pour uniformiser avec les autres
- [ ] enlever l'espace en trop après (IRSN)
- [ ] modifier la source radon pour linker vers le site irsn (https://www.irsn.fr/FR/connaissances/Environnement/expertises-radioactivite-naturelle/radon/Pages/5-cartographie-potentiel-radon-commune.aspx#.YUyf32aA6dY)
- [ ] mettre une virgule à PM2,5
- [ ] ordonner les polluants selon la liste ici (https://atmo-france.org/lindice-atmo/) qui me semble la plus officielle (et reprise ici aussi : https://www.airparif.asso.fr/indice-atmo)
- [ ] enlever les doubles espaces dans les recommandations (raep)

**Comment by l-vincent-l** [comment]
Je suis un peu chouin-chouin sur le radon.
Que l’on veuille faire un autre affichage sur notre front pourquoi pas, mais ici c’est une API qui re-distribue de l‘information déjà existante, et cette notion de faible, moyen, élevé n’a pas de signification à part chez nous.

**Comment by annepoirot** [comment]
Ces termes sont aussi utilisés par l'IRSN sur cette carte : 
https://www.irsn.fr/FR/connaissances/Environnement/expertises-radioactivite-naturelle/radon/PublishingImages/irsn_figure1-potentiel-radon-formations-geologiques.jpg
=> Tu penses qu'on devrait voir avec eux si c'est ok de les mettre dans l'API ?

**Comment by l-vincent-l** [comment]
Nope, c’est ok, je n’avais pas vu ces termes

**Comment by l-vincent-l** [comment]
Pour les doubles espaces, tu peux préciser sur quelles recommandations ?

**Comment by florianpanchout** [comment]
"En cas d’allergie diagnostiquée,  rincer ses cheveux après une activité physique en extérieur afin d’éliminer les pollens."

**Comment by florianpanchout** [comment]
Je n'arrive toujours pas à accéder à https://staging.api.recosante.beta.gouv.fr/v1/?insee=75056. C'est normal ?

Et il manque toujours validity pour le radon

**Comment by l-vincent-l** [comment]
Désolé, sur staging je travaille sur une branche avec seulement les développements pour l’inscription utilisateur.
Je remonte la branche ne prod dessus pour avoir les dernières évolutions de l’API sur staging

**Comment by l-vincent-l** [comment]
Et la base de données que je prends pour le staging est petite, le nombre de connexions max était dépassé

**Comment by florianpanchout** [comment]
Ça marche. J'ai du mal à comprendre en quoi consiste l'environnement de staging. 

Dans ma tête c'était un duplicata total de la prod à l'exception de :
- L'import automatique des données ASQAA / RAEP, remplacées par des données fixes 
- L'envoi de mail / notification automatique

Avec une branche main et une staging, la dernière sur laquelle tu commit/merges au fur et à mesure, avant de mettre en prod.

Du coup qu'est ce qui existe en staging et qu'est ce qui n'existe qu'en prod ?

**Comment by l-vincent-l** [comment]
C’est ok pour le validity

**Comment by florianpanchout** [comment]
Parfait merci !

**Comment by florianpanchout** [comment]
J'ai une erreur sur https://staging.api.recosante.beta.gouv.fr/v1/?insee=31555 :/

**Comment by l-vincent-l** [comment]
Rah j’ai bien lutté pour trouver l’erreur, ça devrait être bon

**Comment by florianpanchout** [comment]
Toujours rien pour l'Île de France :/ 

https://staging.api.recosante.beta.gouv.fr/v1/?insee=93055

**Comment by l-vincent-l** [comment]
J’avais un problème de recopie de données

**Comment by florianpanchout** [comment]
Erreur sur toutes les villes, prod et staging (https://api.recosante.beta.gouv.fr/v1/?insee=75056)

**Comment by florianpanchout** [comment]
J'ai toujours l'erreur en staging : https://staging.api.recosante.beta.gouv.fr/v1/?insee=75056 :/

**Comment by florianpanchout** [comment]
Possible d'ajouter "l'" devant "Institut de radioprotection et de sûreté nucléaire (IRSN)" ? (et enlever l'espace).

Pour être cohérent avec le RAEP
