### ISSUE TITLE
Le endpoint /stats renvoie une 502

### ISSUE THREAD

**Issue by florianpanchout** [betagouv/recosante-api#245]

**Comment by l-vincent-l** [comment]
les 502 sont des timeouts du au temps de réponse de sendinblue.
Il va falloir soit mettre du cache sur leurs requêtes, soit faire un mécanisme pour lancer les requêtes en background

**Comment by florianpanchout** [comment]
On a besoin de Sendinblue juste pour le taux d'ouverture non ? Est ce que si on n'affichais que le taux d'ouverture de la veille on éliminerais le problème ?

**Comment by florianpanchout** [comment]
Je regarde pour modifier le front pour ne pas attendre le retour de /openings pour afficher le reste
