### ISSUE TITLE
Indice ATMO incorrect le 29/07/2021

### ISSUE THREAD

**Issue by annepoirot** [betagouv/recosante-api#246]
Retour de ATMO Auvergne Rhône Alpes :

Bonjour,
 
Je me permets de vous signaler une erreur dans l’information sur l’indice Atmo aujourd’hui, pour Lyon et pour d’autres communes de la région : l’indice ne peut pas être mauvais si au moins un sous-indice de l’est pas. Par ailleurs, ce jour, l’indice Atmo est « dégradé » sur Lyon.
 
Quelle est la source de l’erreur selon vous ?

=> Si on a une explication, répondre directement à leur mail pendant mes congés :)

**Comment by l-vincent-l** [comment]
L’indice a été mis à jour dans la journée.
Par contre je n’ai pas le mail pour répondre

**Comment by annepoirot** [comment]
Ok je leur ai répondu (c'était sur l'adresse contact).
