### ISSUE TITLE
Uniformiser le format de retour de https://ecosante.beta.gouv.fr/inscription

### ISSUE THREAD

**Issue by florianpanchout** [betagouv/recosante-api#254]
Ce serait plus clean d'avoir "enfants" : ["oui", "aucun"] pour garder le même format que les autres réponses non ?

Et mettre "ville_codes_postaux", "ville_insee" et "ville_nom" dans un seul objet ? En reprenant le format de https://geo.api.gouv.fr/communes

**Comment by florianpanchout** [comment]
Ce serait peut être aussi l'occasion de passer sur une architecture REST classique ?

Avec un endpoint 

`https://api.recosante.beta.gouv.fr/users`

qui remplacerait 

```
https://api.recosante.beta.gouv.fr/inscription/premiere-etape
https://api.recosante.beta.gouv.fr/inscription/
```

**Comment by florianpanchout** [comment]
Avec le nouveau process d'inscription, l'objet user pourrait ressembler à ça : 

```
{
  "activites": ["jardinage", "bricolage"],
  "animaux_domestiques": ["chat", "chien"],
  "chauffage": ["chaudiere"],
  "commune": {
    "code": "25056",
    "nom": "Besançon",
    "codesPostaux": ["25000"],
    "departement": {
      "code": "25",
      "nom": "Doubs"
    }
  },
  "connaissance_produit": ["reseaux_sociaux"],
  "deplacement": ["velo", "tec", "voiture"],
  "enfants": ["oui"],
  "indicateurs": [
    "indice_atmo",
    "raep",
    "indice_uv",
    "vigilance_meteorologique"
  ],
  "indicateurs_frequence": ["quotidien"],
  "indicateurs_media": ["mail"],
  "mail": "florian.panchout@beta.gouv.fr",
  "recommandations": ["oui"],
  "recommandations_frequence": ["hebdomadaire"],
  "recommandations_media": ["mail"]
}
```

Qu'est ce que tu en penses ? Je ne sais pas ce qui est le mieux / plus simple : mettre 3 propriétés pour les indicateurs (indicateurs, indicateurs_frequence, indicateurs_media) ou tout mettre dans un objet indicateur (même questions pour recommandations)

**Comment by l-vincent-l** [comment]
J’ai fait une première version de l’API qui est dispo en staging.
La documentation est ici https://staging.api.recosante.beta.gouv.fr/users/swagger/ui

**Comment by l-vincent-l** [comment]
J’avais zappé les nouvelles données à ajouter, je fais ça.

**Comment by l-vincent-l** [comment]
Désolé, je n’avais pas vu le commentaire avant de répondre hier.
ça me parait bien comme format, ça m’arrange que les données liées aux indicateurs et recommandations soient plates.

Je viens de pousser en staging la nouvelle version de l’API.

**Comment by florianpanchout** [comment]
Du coup comment j'accède à un user ? https://staging.api.recosante.beta.gouv.fr/users/o96mGLm8 me renvoie une erreur ?

**Comment by l-vincent-l** [comment]
je n’avais pas fait ce endpoint.
Je le fais

**Comment by l-vincent-l** [comment]
C’est fait.

**Comment by florianpanchout** [comment]
J'ai toujours une erreur :/

**Comment by florianpanchout** [comment]
Dans la doc :

- [ ] Il y a "sport" en option possible pour "deplacement"
- [ ] Il n'y a pas l'option "non" pour "recommandations"
- [ ] Mettre "alerte" plutôt que "pollution" pour la fréquence (vu qu'il ne s'agit pas que des épisodes de pollution)

**Comment by florianpanchout** [comment]
Je ne peux pas accéder à https://staging.api.recosante.beta.gouv.fr/users/o96mGLm8 en POST. Je rate quelque chose ?

**Comment by l-vincent-l** [comment]
Tu peux le faire directement depuis `/users/` en réutilisantl la même adresse mail (vu que de toute façon pour l’instant tu peux updater un compte comme ça, ça ne change pas grand chose)

**Comment by florianpanchout** [comment]
Ça marche ! Et comment j'update l'adresse email ?

**Comment by florianpanchout** [comment]
J'ai une erreur CORS quand j'essaie d'accéder à https://staging.api.recosante.beta.gouv.fr/users/ en POST

**Comment by l-vincent-l** [comment]
tu peux me coller l’erreur ?

**Comment by florianpanchout** [comment]
`Access to XMLHttpRequest at 'https://staging.api.recosante.beta.gouv.fr/users' from origin 'http://localhost:8000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: Redirect is not allowed for a preflight request.
`

Avec comme payload : 

```
commune: "31555"
indicateurs: ["indice_atmo"]
indicateurs_frequence: ["alerte"]
indicateurs_media: ["notifications_web"]
mail: "florian.panchout@beta.gouv.fr"
recommandations: ["non"]
```

**Comment by l-vincent-l** [comment]
Est-ce que tu peux changer le point d’entrée pour `https://staging.api.recosante.beta.gouv.fr/users/` avec le trailing slash.
et le commune ça va être `"commune" : {"code": "31555"}`

**Comment by florianpanchout** [comment]
Et https://staging.api.recosante.beta.gouv.fr/users/o96mGLm8 fonctionne en POST 🎉

**Comment by florianpanchout** [comment]
Mais https://staging.api.recosante.beta.gouv.fr/users/o96mGLm8 m'oblige à lui envoyer l'email pour mettre à jour n'importe quel champ :(

**Comment by l-vincent-l** [comment]
C’est fixé

**Comment by florianpanchout** [comment]
Ça fonctionne maintenant mais je ne peux plus revenir à mon adresse mail (florian.panchout@beta.gouv.fr) depuis que je l'ai changé sur https://staging.api.recosante.beta.gouv.fr/users/o96mGLm8

(toute autre adresse a l'air de fonctionner)

**Comment by l-vincent-l** [comment]
Tiens la réponse par mail n’a pas fonctionné.
Un autre utilisateur a déjà cette adresse mail. Tout fonctionne donc comme prévu !

**Comment by florianpanchout** [comment]
Donc hier, j'avais un compte avec comme adresse email florian.panchout@beta.gouv.fr (uid : `o96mGLm8`, toujours le même)

Je fais une modification via https://staging.api.recosante.beta.gouv.fr/users/o96mGLm8 pour la changer

Dans la foulée, je refais une deuxième modification pour remettre florian.panchout@beta.gouv.fr

Donc 
- Soit quelqu'un s'est inscrit sur le staging pendant les 4 secondes entre mes deux requêtes.
- Soit j'ai pu, à un moment antérieur, créer un nouveau compte avec une adresse email déjà utilisée

Dans les deux cas, on a un problème

**Comment by l-vincent-l** [comment]
Je n’ai pas accès à l’historique des données.
À moins que tu es un cas reproductible dans l’état actuel de la prod, je ne pense pas qu’on est de problème.

Je ne peux pas enregistrer de nouvel utilisateur avec cette adresse mail, ni changer un utilisateur existant avec cette adresse mail.

Sauf si tu as un cas que je peux reproduire, je ne pense pas qu’il y ait de problème

**Comment by florianpanchout** [comment]
Ça marche. J'ai du me tromper en écrivant mon nom.

Possible de supprimer l'autre compte associé à l'email florian.panchout@beta.gouv.fr ?

**Comment by l-vincent-l** [comment]
J’ai changé son mail

**Comment by florianpanchout** [comment]
Parfait, merci !
