### ISSUE TITLE
Corriger les fautes d'orthographes des recommandations (+ standardiser formatage)

### ISSUE THREAD

**Issue by florianpanchout** [betagouv/recosante-api#258]
Sans toucher au contenu (pour l'instant), il faudrait faire une repasse sur l'ensemble des recommandations pour corriger à minima les fautes évidentes.

Et le formatage des précisions est aléatoire. Il faudrait se mettre d'accord et repasser sur chaque. Je propose :
- mettre tous les contenus textes dans des balises `<p>`
- afficher les sauts de lignes via des `<br/>`

Et est ce que ça a encore un sens de garder "recommandation" et "recommandation_sanitized" ? Est ce qu'on ne mergerais pas les deux ?

**Comment by florianpanchout** [comment]
- Mettre les paragraphes dans des balises `<p>`
- Afficher les sauts de lignes via des `<br/>`
- Mettre les listes dans des `<ul>` (et les items dans des `<li>`) . 
- Mettre une espace insécable fine `&#8239;` avant les ponctuations qui en ont besoin
- Mettre une espace insécable `&#160;` avant le dernier mot du paragraphe (pour qu'il ne se retrouve pas seul à la ligne)
- Afficher le gras via des balises `<strong>`
- Afficher l'italique via des balises `<i>`

**Comment by florianpanchout** [comment]
Décision 06/09 : Utilisation du markdown plutôt que du html

**Comment by annepoirot** [comment]
**Type de balises qu'on a actuellement :** 

1) Des balise <p> dans les précisions sur une partie des paragraphes seulement pour une centaine de recos.
` ℹ️ L'air intérieur que nous respirons 80 % de notre temps (chez nous, au travail, dans les transports en commun...) est 5 à 7 fois plus pollué que l'air extérieur. <p>💡 En plus de l'air extérieur qui y pénètre s'ajoutent des polluants spécifiques de l’air intérieur (polluants chimiques, fibres, particules...). Une exposition répétée et durable, même à des doses parfois très faibles, peut aggraver ou être à l’origine de pathologies chroniques. </p> 
`
2) Des balises <ul> et/ou <li> dans 3 recos
`ℹ️ Les symptômes en cas d'allergie aux pollens sont : <ul> <li>crises d’éternuement ;</li> <li>nez qui gratte, parfois bouché ou qui coule clair ;</li> <li>yeux rouges, qui démangent ou qui larmoient ;</li> <li>en association éventuelle avec une respiration sifflante ou une toux.</li> </ul> <p> `
ou bien
`<p><li>En cas de gêne respiratoire ou cardiaque, prendre conseil auprès d’un professionnel de santé.</li> <li>Privilégier des sorties plus brèves et celles qui demandent le moins d’effort.</li> <li>Maintenir les activités physiques et sportives intenses (dont les compétitions) à l’intérieur.</li></p> <p> Si vous êtes une personne sensible ou vulnérable : <ul> <li>prendre conseil auprès de votre médecin pour savoir si votre traitement médical doit être adapté le cas échéant ; </li> <li>éviter les sorties durant l’après-midi lorsque l’ensoleillement est maximum ;</li> <li>éviter les activités physiques et sportives intenses (dont les compétitions) en plein air ; celles peu intenses à l’intérieur peuvent être maintenues.</li></ul></p>`

3) Des balises pour les liens dans une trentaine de recos
`ℹ️ 10 km/h en moins permettent d’économiser jusqu’à 5 litres de carburant et de réduire de 12,5 % (soit 12 kg) les émissions de CO2 sur 500 km. <a href="https://huit.re/voiture-eco">Plus d'informations</a>.`

=> Du coup @l-vincent-l j'attend que tu me dises de ton côté quand tu as pu voir ce qu'on peut automatiser dans les modifications. Et si ensuite si ya besoin de repasser dessus pour modif ou relire tu me dis et je m'en occupe. Dans tous les cas on s'est dit qu'on attendait l'environnement de staging.

**Comment by l-vincent-l** [comment]
J’ai poussé en staging les recommandations converties en markdown, et on peut faire un aperçu

**Comment by florianpanchout** [comment]
Ou est ce que je peux voir la page admin en staging ? Je ne la trouve pas :(

**Comment by florianpanchout** [comment]
@l-vincent-l https://github.com/betagouv/recosante-api/issues/258#issuecomment-929124982
