### ISSUE TITLE
Ajouter un endpoint pour enregistrer l'abonnement push

### ISSUE THREAD

**Issue by florianpanchout** [betagouv/recosante-api#259]
Il faudrait pouvoir stocker l'abonnement quelque part (https://developers.google.com/web/fundamentals/push-notifications/subscribing-a-user#send_a_subscription_to_your_server).

Sachant qu'un utilisateur peut en avoir plusieurs (un par device / browser).

Soit via https://ecosante.beta.gouv.fr/inscription, soit via un nouvel endpoint. Je ne sais pas trop ce qui est le plus logique / propre.

**Comment by florianpanchout** [comment]
Comment je fais pour envoyer plusieurs abonnements ? webpush_subscription_info est une string dans la doc

(ce ne serait pas plus logique de passer par un endpoint du style /users/:uid/pushsubscriptions ? Vu qu'il peut y en avoir plusieurs et que le front n'a pas d'interêt à les récupérer)

**Comment by l-vincent-l** [comment]
J’avais zappé, l’aspect plusieurs notifications, mais c’est pas grave, je vais ajouter un `s` à l’attribut.
Je vais laisser comme tel, et gérer de mon côté pour regarder si on a déjà la notification pour l’ajouter au besoin.
