### ISSUE TITLE
Rendre la newsletter hebdomadaire

### ISSUE THREAD

**Issue by florianpanchout** [betagouv/recosante-api#261]
Pour les gens qui ont choisi un mail hebdomadaire, envoyer :
- un mail hebdomadaire tous les lundi (template à définir)
- un mail en cas d'alerte pollution / pollens (conditions et template à définir)

**Comment by florianpanchout** [comment]
Après point 09/09 : 

Newsletter uniquement hebdomadaire avec un nouveau template et du contenu pouvant être personnalisé selon le profil utilisateur (mais pas selon les indicateurs du jour).

Template et contenu à définir au point de 14/09.

**Comment by florianpanchout** [comment]
5 cas de figures : 

- Abonné aux indicateurs quotidien (mail ou notification)
- Abonné aux indicateurs alerte (mail ou notification)
- Abonné aux indicateurs quotidien (mail ou notification) + Mail hebdomadaire
- Abonné aux indicateurs alerte (mail ou notification) + Mail hebdomadaire
- Abonné au mail hebdomadaire

**Comment by annepoirot** [comment]
Dans un premier temps on pourra faire un envoi manuel si besoin

**Comment by annepoirot** [comment]
On définit :
- un ordre d'enchaînement des newsletter pour que l'utilisateur suive un parcours de sensibilisation
- les trois premières newsletter sont envoyées par défaut à tout nouvel utilisateur 
- Les utilisateurs reçoivent les newsletter selon le parcours définit ensuite. Ce parcours peut être décalé en fonction du profil de l'utilisateur. 
- les newsletter sont envoyées en fonction du profil de l'utilisateur => on envoie une newsletter vélo aux personnes qui ont déclaré faire du vélo. Si une personne a déclaré faire du vélo et utiliser la voiture, il reçoit les deux newsletter (pas le même jour).
- Certaines newsletter "spéciales" car elles correspondent à un calendrier. Par exemple, la newsletter sur le chauffage ne peut être reçue qu'entre octobre et mars.
- si un utilisateur s'inscrit à une borne dans le calendrier d'une newsletter spéciale et du coup le dépasse => elle n'est pas envoyée
Procédé pour commencer (à détailler) : 
- Rédaction des newsletter dans sendinblue
- Remplissage dans l'admin Recosanté 
- échange sur les newsletter hebdo via github

TO DO:
- [ ] établir la liste de toutes les newsletter
- [ ] identifier les newsletter spéciales et leur calendrier 
- [ ] rédiger la troisième sur les sources de pollution
- [ ] Définir le processus de validation d'une newsletter hebdo

On se recale un point pour valider avec @florianpanchout et discuter du procédé

**Comment by annepoirot** [comment]
En terme de process, lorsqu'une newsletter est validée, quel serait le plus facile pour vous passer la main ?

Concrètement le template de la newsletter hebdo est déjà fait donc je me disais qu'on pourrait simplement créer chaque newsletter à partir du template sur sendinblue. Est-ce qu'on laisse chaque newsletter du coup dans la catégories template de sendinblue ?

**Comment by florianpanchout** [comment]
À définir. Je pense aussi que le plus simple serait effectivement de créer des nouveaux emails dans Sendinblue puis de renseigner l'id du template quelque part dans l'api

**Comment by annepoirot** [comment]
La newsletter hebdo est envoyée aux personnes qui ont accepté de recevoir la newsletter hebdo => regarder en back le nombre de personnes ayant refusé de la recevoir. 
Pour les autres, on envoie la NL hebdo.

Dans un premier temps : 
- On créé les templates dans sendinblue pour chaque newsletter en commençant par le numéro de la newsletter
- On ajoute un tag "Hebdo" aux templates
- La newsletter est envoyée en fonction de l'ordre d'envoi établi à partir du titre des templates
