### ISSUE TITLE
Gérer l'envoi des indicateurs

### ISSUE THREAD

**Issue by florianpanchout** [betagouv/recosante-api#262]
Pour les gens qui le souhaitent, envoi quotidien d'une notification avec les indicateurs du jour 

(suggestion de design ici : https://recosante.cleverapps.io/)

**Comment by florianpanchout** [comment]
Après point 09/09 :

Envoi des indicateurs (du jour et de la commune) sélectionnés par l'utilisateur, à la fréquence souhaitée (quotidien ou alerte) et via le média souhaité (mail ou notification web)

**Comment by annepoirot** [comment]
Je me demandais : pour les utilisateurs qui choisissent tous les jours + notifications, qu'est ce qu'ils recoivent comme recommandation ? Quid des recommandations-indicateurs ?

**Comment by florianpanchout** [comment]
Issue divisée en 4 (#268, #269, #270, #271)
