### ISSUE TITLE
Ajouter un endpoint permettant de supprimer son compte

### ISSUE THREAD

**Issue by florianpanchout** [betagouv/recosante-api#263]
Et toutes les données associées.

(c'est ce qui me semble être la chose à faire niveau RGPD mais je suis évidemment preneur de tes recos)

**Comment by l-vincent-l** [comment]
J’ai ajouté deux endpoints pour activer et désactiver un compte.

Pour désactiver un compte il on peut appeler `POST /users/<uid>/_deactivate`
Pour résactiver un compte il on peut appeler `POST /users/<uid>/_reactivate`

Si l’appel ce passe correctement ils répondent tous les deux avec le nouvel objet user et un code 200.

J’ai aussi ajouté un attribut `active` à la réponse pour savoir si un utilisateur est actif

**Comment by florianpanchout** [comment]
J'ai mis en place le process de désactivation / réactivation en front.

Le mail à envoyer à l'utilisateur à la désactivation est ici : https://my.sendinblue.com/camp/template/1594/message-setup?editor=v6

**Comment by l-vincent-l** [comment]
Le mail s’envoie à la suite d’une désinscription
