### ISSUE TITLE
Rédiger les recommandations pour le dashboard

### ISSUE THREAD

**Issue by annepoirot** [betagouv/recosante-api#266]
ajouter recommandation radon au dashboard 
et avoir plus de reco (diviser les reco, api grave de pas avoir un truc exhaustif)

**Comment by annepoirot** [comment]
Les recommandations sont ici : https://pad.incubateur.net/InAK5Ku9QGK5v3FbeU-B4A?edit
Elles ont été ajoutées dans le catalogue de reco avec le filtre dashboard

**Comment by florianpanchout** [comment]
Elle s'affiche sur le dashboard. Ça rend bien mieux je trouve :) Juste il faudra mettre des target="_blank" dans les liens (à traiter dans l'issue https://github.com/betagouv/recosante-api/issues/258
