### ISSUE TITLE
Les liens des recommandations ne s'affichent pas dans le mail

### ISSUE THREAD

**Issue by annepoirot** [betagouv/recosante-api#27]
Soit on passe que par des URL raccourcie, soit est-ce qu'il n'y a pas un autre moyen ?

**Comment by DavidBruant** [comment]
c'est toujours d'actualité ?

**Comment by annepoirot** [comment]
Pour le moment j'ai prévu de passer par les URL raccourcie... de toute manière le format csv lit que le texte non ?

**Comment by DavidBruant** [comment]
oui, le csv, c'est du texte

**Comment by annepoirot** [comment]
Alors restons sur les URL raccourcie pour le moment ? Ou bien tu penses à une autre solution ?

**Comment by annepoirot** [comment]
L'idéal serait un lien hypertexte
