### ISSUE TITLE
Gérer l'envoi des indicateurs en cas d'alerte

### ISSUE THREAD

**Issue by florianpanchout** [betagouv/recosante-api#270]
Sur la base de #269, ajouter la possibilité de choisir la fréquence de réception des indicateurs (quotidien ou alerte)

@MarinePurson @annepoirot Il faut définir ce qui constitue une alerte, pour la QA et le RAEP

**Comment by MarinePurson** [comment]
Pour la QA, il y a les pics de pollution en premier lieu.
Ensuite pour l'indice ATMO et le RAEP cela dépend des profils des utilisateurs (personnes sensibles ou non, personnes allergiques ou non). @annepoirot doit avoir l'arbre qu'elle avait réalisé le sujet avec Morgane.

**Comment by florianpanchout** [comment]
Yes mais on a plus ces infos maintenant, vu que l'on a pas le droit de les demander :/ 

Pour le RAEP ça me semble "logique" de penser que si les gens s'y abonnent c'est parce qu'ils sont allergique au pollens.

Pour l'indice Atmo, c'est plus compliqué. Perso je mettrais la limite à "mauvais" (en me disant que les gens vraiment sensibles choisiraient la fréquence quotidienne). Mais je n'ai clairement pas un avis éclairé sur le sujet

**Comment by MarinePurson** [comment]
Pour le RAEP, il y a des subtilités : les personnes allergiques sont affectées à partir d'un certain seuil ( dès le 1 il me semble) mais tu peux avoir des sensibilités lorsque le taux est très élevé même si tu n'es pas diagnostiqué allergique...

**Comment by florianpanchout** [comment]
Si tu es affecté dès le 1 tu choisis quotidien non ? Si on met l'alerte à 1 il n'y a aucune différence entre quotidien et alerte

**Comment by annepoirot** [comment]
Je dirais Mauvais pour la QA et 4 pour le RAEP => ce sont les seuils qui avaient été validés par le MSS lors des échanges sur l'envoi de recommandations.

**Comment by florianpanchout** [comment]
A voir comment on présente ça mais ok sur le principe

**Comment by annepoirot** [comment]
Attention, si un utilisateur s'est inscrit en "alerte" pour indice atmo et RAEP, il reçoit les deux seulement s'il y a une alerte sur les deux. S'il y a uniquement un épisode de pollution mais que le RAEP est =2 par exemple, lui montrer uniquement l'épisode de pollution.

**Comment by l-vincent-l** [comment]
Même si la personne dit vouloir recevoir le RAEP ?

**Comment by annepoirot** [comment]
@l-vincent-l doit vérifier que les indicateurs alertes s'envoient bien (épisode de pollution et RAEP>4). Attention de n'envoyer que l'indicateur qui est en alerte (cf commentaire précédent)

**Comment by annepoirot** [comment]
Deux points dans l'envoi de la newsletter avec l'épisode de pollution :

1) "En savoir plus" dans l'encadré 
On peut effectivement ne plus renvoyer à l'AASQA dans ce cas là vu qu'on y renvoie après non ? Peut-être qu'on peut ne pas mettre de "en savoir plus" pour le moment. Qu'en pensez-vous @MarinePurson @mariegasnier1.

2) On a un bug sur les recommandations qui ne sont pas les recommandations réglementées
Il semblerait que dans l'envoi d'aujourd'hui, il y ait un mélange de recommandations qui ne sont pas les bonnes. 

Il faut changer par : 

Pour PM10, NO2 et SO2 c'est [ces recos ](https://api.recosante.beta.gouv.fr/recommandations/edit/4792?search=&status=published&objectif=None&type=None&medias=dashboard): 
>En cas de gêne respiratoire ou cardiaque, prendre conseil auprès d’un professionnel de santé. * Privilégier des sorties plus brèves et celles qui demandent le moins d’effort. * Réduire, voire reporter, les activités physiques et sportives intenses (dont les compétitions). Si vous êtes une personne sensible ou vulnérable : * prendre conseil auprès de votre médecin pour savoir si votre traitement médical doit être adapté le cas échéant ; * éviter les zones à fort trafic routier, aux périodes de pointe ; * privilégier les activités modérées. 

Pour O3 c'est [ces recos](https://api.recosante.beta.gouv.fr/recommandations/edit/4793?search=&status=published&objectif=None&type=None&medias=dashboard) :
>En cas de gêne respiratoire ou cardiaque, prendre conseil auprès d’un professionnel de santé. * Privilégier des sorties plus brèves et celles qui demandent le moins d’effort. * Maintenir les activités physiques et sportives intenses (dont les compétitions) à l’intérieur. Si vous êtes une personne sensible ou vulnérable : * prendre conseil auprès de votre médecin pour savoir si votre traitement médical doit être adapté le cas échéant ; * éviter les sorties durant l’après-midi lorsque l’ensoleillement est maximum ; * éviter les activités physiques et sportives intenses (dont les compétitions) en plein air ; celles peu intenses à l’intérieur peuvent être maintenues.

**Comment by mariegasnier1** [comment]
Au lieu du "En savoir plus" dans le premier encadré, on peut renvoyer vers la définition des PM10. 

Toutes les recos doivent être listées en même temps, sous l'indicateur ?

**Comment by annepoirot** [comment]
Ca me va de renvoyer vers la définition des PM10 sur notre site.

Oui toutes les recommandations doivent être listées normalement, enfin c'est ce que j'avais compris du point de vue réglementaire, non ?

**Comment by mariegasnier1** [comment]
D'ailleurs, on peut changer "Un épisode de pollution aux particules fines est prévu aujourd'hui dans votre **département**." par "Un épisode de pollution aux particules fines est prévu aujourd'hui dans votre **commune**" ? .

**Comment by mariegasnier1** [comment]
> Ca me va de renvoyer vers la définition des PM10 sur notre site.
> 
> Oui toutes les recommandations doivent être listées normalement, enfin c'est ce que j'avais compris du point de vue réglementaire, non ? Sûrement ! C'était plutôt Morgane qui gérait les recos

**Comment by annepoirot** [comment]
Alors ça pour le coup c'était des échanges qu'on avait eu avec ATMO il y a longtemps où ils nous avaient demandé de mettre département, est-ce que tu te souviens pourquoi déjà @MarinePurson ?
Après comme il y a écrit au dessus la commune, est-ce qu'on ne peut pas simplement mettre "Un épisode de pollution aux particules fines est prévu aujourd'hui" ?

**Comment by annepoirot** [comment]
> > Oui toutes les recommandations doivent être listées normalement, enfin c'est ce que j'avais compris du point de vue réglementaire, non ? _**Sûrement ! C'était plutôt Morgane qui gérait les recos**_

Est-ce que tu as la possibilité de re vérifier facilement côté MSS ?

**Comment by mariegasnier1** [comment]
Oui très bien. Mais je ne comprends pas pourquoi on ne délivre pas toutes ces recommandations réglementées sur le dashboard alors ? 

![image](https://user-images.githubusercontent.com/89836591/141097775-7595b182-6003-4d67-b521-8482b951f736.png)

**Comment by annepoirot** [comment]
C'est encore en cours de développement, mais oui l'objectif sera de les afficher aussi sur le dashboard. On en discute ici : https://github.com/betagouv/recosante/issues/88

**Comment by annepoirot** [comment]
Du coup pour résumer : 
Mais du coup dans le mail, est ce que ce n'est pas bizarre d'avoir les recommandations réglementées sur les épisodes de pollution sous l'indice et non pas sous l'épisode... ?

**Comment by mariegasnier1** [comment]
- D'accord très bien, je vois en effet l'intérêt de mettre les recommandations dans l'encadré rouge
- Pour pas renvoyer vers la page du MSS sur les reco en cas d'épisode de pollution. Juste, ATMO ne dispose pas plus d'informations que nous, et ça peut être confus pour l'utilisateur qu'on le renvoie à une information similaire

**Comment by MarinePurson** [comment]
- Pour les recos, il faut qu'elles figurent après le pic de pollution (que ce soit dans le mail ou sur le dashboard) et pas sous l'indice (un indice mauvais n'est pas égal à un pic de pollution).
- Toutes les recos doivent être listées en cas d'épisode de pollution.
- Je ne me souviens pas pourquoi "département" mais ne peut-on pas écrire "Un épisode de pollution aux particules fines est prévu aujourd'hui + commune" ?

**Comment by florianpanchout** [comment]
Par contre ici c'est pour l'envoi des indicateurs pour les gens qui ont choisi de ne les recevoir qu'en cas d'alerte :) 

J'ai créé cette issue pour l'affichage des épisodes de pollution dans le mail, en essayant de synthétiser vos échanges : https://github.com/betagouv/recosante-mail/issues/63

**Comment by florianpanchout** [comment]
J'ai reçu une notification aujourd'hui alors que je suis abonné en fréquence alerte pour la ville de Toulouse (ou il n'y a pas d'alerte)

**Comment by florianpanchout** [comment]
@l-vincent-l Du coup qu'en est il de cette issue ? Est ce que les gens qui souhaitent recevoir les indicateurs par email uniquement en cas d'alerte les reçoivent bien ? (et ne reçoivent que ceux en alerte)

**Comment by l-vincent-l** [comment]
Il y a un ancien fonctionnement qui est toujours en place qui envoie en cas d’alerte s’il y a un indice dégradé ou plus haut.

Est-ce que l’on veut garder ce comportement ?

**Comment by florianpanchout** [comment]
Nope, on n'envoie l'indice ATMO qu'en cas d'épisode de pollution
