### ISSUE TITLE
Ajouter la possibilité de recevoir les indicateurs via notifications web

### ISSUE THREAD

**Issue by florianpanchout** [betagouv/recosante-api#271]
Sur la base de #270, ajouter la possibilité de recevoir des notifications web plutôt que des mails, contenant les indicateurs choisis sans les détails ni les recommandations et linkant vers le dashboard de la ville.

**Comment by florianpanchout** [comment]
Ça marche ! Je regarde si j'arrive à trouver quelque chose et on en reparle demain après le standup si ça te va

Je l'enlève de priorité (parce qu'on en a besoin pour jeudi et pas mercredi)

**Comment by florianpanchout** [comment]
Quelle est le format de `data` dans https://github.com/betagouv/recosante-api/blob/main/ecosante/newsletter/tasks/send_webpush_notifications.py ? 

Si on mets un objet statique du style 
```
{
    "body": "test",
    "link: "https://recosante.beta.gouv.fr"
}
```
ça passe toujours pas ?

**Comment by l-vincent-l** [comment]
Dans le test tu peux changer l’indicateur normalement ça fonctionne.
Et j’ai fixé l’URL

**Comment by l-vincent-l** [comment]
Normalement ça prend l’indice de la ville de la personne sélectionné.
Tu as testé avec quelle adresse ?
