### ISSUE TITLE
Migrer les utilisateurs en prod

### ISSUE THREAD

**Issue by l-vincent-l** [betagouv/recosante-api#273]
Les utilisateurs actuels sont inscrits avec 
 * une fréquence quotidienne
 * Les indicateurs :
    - indice_atmo
    - raep ( pour les personnes souhaitant recevoir des recommandations sur le raep)

**Comment by annepoirot** [comment]
et épisodes de pollution aussi

**Comment by florianpanchout** [comment]
Ah oui tiens. À qui on envoie les épisodes de pollution aux gens ? Seulement ceux qui ont choisi l'indice ATMO ou tout le monde ?

**Comment by annepoirot** [comment]
Pour moi le cas indice atmo + en cas d'alerte ça veut dire qu'on envoie l'indice atmo à partir de mauvais + les épisodes de pollution. 
Par contre est-ce que dans le process d'inscription on les différencie... je dirais plutôt non.

**Comment by florianpanchout** [comment]
Je pense que dans la tête des gens (et dans la mienne aussi) : "épisode de pollution" = "alerte indice Atmo", donc ça me semble compliqué de séparer à l'inscription.

(D'ailleurs qu'est ce qui défini un épisode de pollution ?)

**Comment by annepoirot** [comment]
Oui je suis d'accord. Ce qui définit un épisode de pollution c'est les seuil de concentration de polluants. https://www.atmo-hdf.fr/tout-savoir-sur-l-air/episode-de-pollution.html
