### ISSUE TITLE
Ajouter  un envoie des indicateurs manuel

### ISSUE THREAD

**Issue by l-vincent-l** [betagouv/recosante-api#274]
Pour les plateformes de dev et staging.
Ajouter la possibilité d’envoyer une newsletter à un utilisateur en particulier pour tester les fonctionnalités

**Comment by l-vincent-l** [comment]
Ajouter à l’interface d’adminstration

**Comment by florianpanchout** [comment]
> Quel template de mail cet envoi utilise ? Est ce que c'est possible d'en prendre un différent de la newsletter quotidienne que l'on utilise actuellement.

Modifiable via variable env

**Comment by florianpanchout** [comment]
Adapter pour prendre en compte le choix du média (email ou notification)

**Comment by florianpanchout** [comment]
Cool !

On peut le mettre dans backlog, ça me semble très secondaire

**Comment by florianpanchout** [comment]
Deux trucs (testé sur le staging) : 
- Je ne reçois que la pollution de l'air (et toujours "Moyen"). J'imagine que c'est parce que tu envoies un truc statique pour l'instant ?
- Le lien renvoie une 404 à cause de la capitale dans le nom de la ville. J'ai mis à jour le sw mais si tu peux faire la modif de ton côté aussi c'est cool (flemme d'expliquer aux gens comment mettre à jour son service worker)
