### ISSUE TITLE
Fixer l’import de données dans staging

### ISSUE THREAD

**Issue by florianpanchout** [betagouv/recosante-api#276]
Sur 

https://staging.api.recosante.beta.gouv.fr/v1/?insee=75056

https://staging.api.recosante.beta.gouv.fr/v1/?insee=67482

**Comment by l-vincent-l** [comment]
Les données sont à nouveau importées

**Comment by florianpanchout** [comment]
L'api en staging renvoie une 500. J'ai switché sur l'api de prod pour l'instant
