### ISSUE TITLE
Les données de Martinique et Guadeloupe ne s'affichent pas sur le dashboard

### ISSUE THREAD

**Issue by annepoirot** [betagouv/recosante-api#278]
Est-ce que c'est un problème de flux de données ?

**Comment by l-vincent-l** [comment]
Les données sont bien présentes en base, elle s’affiche pour la Martinique, mais pas pour la guadeloupe

**Comment by florianpanchout** [comment]
J'ai bien les données pour la Guadeloupe : https://recosante.beta.gouv.fr/place/97105/basse-terre/

J'imagine que c'était lié à https://github.com/betagouv/recosante/issues/143
