### ISSUE TITLE
[outil csv] API airparif fonctionne plutôt l'après-midi, plutôt pas le matin

### ISSUE THREAD

**Issue by annepoirot** [betagouv/recosante-api#28]
Quand Mauranne télécharge les CSV, l'API de airparif semble fonctionné. Mais pas de mon côté.

**Comment by DavidBruant** [comment]
Pas en confiance sur Airparif et notre capacité à récupérer automatiquement de manière fiable la donnée

Ptèt une solution en attendant, ça serait que l'outil csv : 
1. liste les villes/régions pour lesquelles on n'a pas trouvé la donnée de qualité de l'air
2. génère un formulaire genre : 
```
La qualité de l'air en Ile-de-France aujourd'hui est : 
⦾ bonne
⦾ moyenne
⦾ mauvaise
La qualité de l'air en Occitanie aujourd'hui est : 
⦾ bonne
⦾ moyenne
⦾ mauvaise
```
3. remplisse les csv de sortie en fonction de ces réponses (plutôt que d'avoir à faire tout ça à la main)

T'en penses quoi, @annepoirot ?

**Comment by DavidBruant** [comment]
Solution intérmédiaire : https://github.com/betagouv/ecosante/issues/31

**Comment by annepoirot** [comment]
Utiliser les données de prévision
