### ISSUE TITLE
Plus de données pour Grand Est (en dehors de 15 agglomérations)

### ISSUE THREAD

**Issue by florianpanchout** [betagouv/recosante-api#280]
https://api.recosante.beta.gouv.fr/v1/?insee=08341

**Comment by l-vincent-l** [comment]
[Le flux](https://data-atmograndest.opendata.arcgis.com/datasets/ind-grandest-4j) qui diffuse la donnée pour 4j pour toutes le communes du Grand Est n’est plus mis à jour.
Pour fixer ça pour la plupart des villes j’utilise [ce flux](https://data-atmograndest.opendata.arcgis.com/datasets/ind-grandest-5j/explore?location=48.688594%2C5.935304%2C8.71) mais qui ne concerne que les 15 plus grandes agglomérations.
