### ISSUE TITLE
Erreur 500 sur la prod

### ISSUE THREAD

**Issue by florianpanchout** [betagouv/recosante-api#281]
J'ai des erreurs 500 intermittentes  sur https://api.recosante.beta.gouv.fr/v1/?insee=75056

**Comment by florianpanchout** [comment]
Erreur 500 sur toutes les communes : https://recosante.beta.gouv.fr/place/75056/paris/

**Comment by florianpanchout** [comment]
Erreur 500 sur https://api.recosante.beta.gouv.fr/v1/?insee=93055

**Comment by fcoufour** [comment]
Bien vu @florianpanchout.

2 problèmes à l'origine de ceci :
- bug lors du calcul de la couleur globale dans le cas où il n'y a pas de phénomènes
- il n'y a jamais eu de phénomènes pour 92, 93 et 94 car il ne sont pas envoyé dans le fichier XML qui nous alimente, il est nécessaire de faire un cas particulier pour Paris et petite couronne pour que cela corresponde au site Vigilance de Météo France

@l-vincent-l a patché ici : https://github.com/betagouv/indice_pollution/pull/41
