### ISSUE TITLE
Changement catégorisation media pour les recommandations

### ISSUE THREAD

**Issue by l-vincent-l** [betagouv/recosante-api#282]
Les recommandations qui étaient envoyées dans le dashboard sont maintenant aussi envoyées dans la newsletter quotidienne.

Voici donc une proposition d’évolution : 
 - [x] Les recommandations peuvent avoir plusieurs médias
 - [x] Ajout des médias : `newsletter_hebdo`, `newsletter_quotidienne`
 - [x] Les recommandations avec pour media `dashboard` ont maintenant `newsletter_quotidienne` aussi en  média
 - [ ] Voir ce qu’on fait pour les recommandations `widget`

**Comment by annepoirot** [comment]
- Les recommandations widget peuvent être supprimées si elles sont bien des doublons.
- Je me demandais quand même, là on part sur 0 personnalisation dans les reco-indicateurs. Mais en même temps j'ai peur que de la manière dont son rédigé les reco-indicateurs, il y ait quand même une forte impression de redondance similaire à ce qu'on avait avant. Peut-être qu'il faudrait d'autre formulation plus direct (par ex : tout va bien, vous pouvez faire du sport).

**Comment by florianpanchout** [comment]
On a maintenant un seul type de recommandations qui s'affiche dans le mail indicateurs et sur le dashboard / widget. Donc pas de recommandations `newsletter_hebdo`.

Peut être laisser la possibilité de séparer ces deux cas (mail indicateur et dashboard / widget) pour une évolution future effectivement.

(à noter que newsletter_quotidienne n'est pas le bon terme puisque l'on envoie ces recommandations aussi pour le mail alerte indicateurs)

**Comment by annepoirot** [comment]
Yes et le problème là aussi c'est que je n'arrive plus à accéder au catalogue dans son ensemble une fois que j'ai cliqué sur un type de média. 

Si on garde ces trois options : 
- Tous les médias
- mail indicateur 
- dashboard

=> Alors on aura des recommandations identiques entre dashboard et mail indicateurs. Est-ce que ce n'est pas plus logique de simplement faire une option qui n'est pas en fonction du média mais du type de recommandation ? 

On aurait une catégorie, par exemple "reco-indicateur", qui englobe les recommandations envoyées sur le dashboard et dans la newsletter (alerte et quotidien confondu). 

J'arrive pas à savoir si c'est mieux de faire ça ou alors l'option précédente ou on sépare quand même dashboard et newsletter. Est-ce qu'on a vocation à avoir des recommandations différentes à un moment entre les deux supports ? J'ai tendance à penser que non.
