### ISSUE TITLE
Ajouter les données d'indice UV dans l'API

### ISSUE THREAD

**Issue by annepoirot** [betagouv/recosante-api#283]
- [x] Table en base de données indice_uv
- [x] Renvoyer ces données via notre API
- [x] Ingestion auto des fichiers CSV livrés par Météo France
- [x] Valider specs techniques avec Météo France
- [x] Intégrer les recommandations via back office
- [ ] Saisir les recommandations sur le back office de production

Voir côté site web : https://github.com/betagouv/recosante/issues/177

Message de Grégory (Météo France) : 
- Je n'avais pas fait attention au 0 qui traînait derrière le code INSEE (c'est une précision interne) : il sera supprimé dans la version finale
- Effectivement, nous utilisons le 20 pour toute la Corse. En fait, les communes de Corse sont classées par ordre alphabétique pour l'ensemble des deux départements (Haute-Corse + Corse du Sud) : en se basant sur les 3 derniers chiffres du code INSEE on retrouve la correspondance.

Je mets la production en intégration sur cette base. Il y aura une petite phase de test pour vérifier que tout fonctionne jusqu'au dépôt sur votre serveur FTP puis un passage en opérationnel assez rapidement derrière.

**Comment by mariegasnier1** [comment]
Hello, 
Pour le seuil d'alerte, il faut communiquer l'indice UV à partir du niveau 3 (dans la mesure où le HCSP recommande des conseils de protection à partir de ce seuil). 

Concernant la valeur des indices, il faut prendre celles de Météo France, à savoir : 
![image](https://user-images.githubusercontent.com/89836591/145182983-3308723b-a588-4c9b-b1c1-f4e48e7ca81e.png)

**Comment by annepoirot** [comment]
[Recommandations dashboard UV.docx](https://github.com/betagouv/recosante-api/files/7897375/Recommandations.dashboard.UV.docx)

**Comment by fcoufour** [comment]
Ci-joint l'avis relatif aux recommandations sanitaires associées aux index UV produit par le HCSP le 02/05/2019 : [hcspa20190502_recommasanitaiassocieauxindexuv.pdf](https://github.com/betagouv/recosante/files/7897416/hcspa20190502_recommasanitaiassocieauxindexuv.pdf).

<img width="805" alt="hcsp-indiceuv" src="https://user-images.githubusercontent.com/23194091/150138983-0745f373-2e73-4cac-b3f4-14bcba5eba7b.png">

**Comment by fcoufour** [comment]
@annepoirot le site de Météo France et le fichier qui va nous alimenter présentent des indices parfois égaux à 0. Il faudrait voir avec le fournisseur ce que ça signifie : absence de mesure ou risque nul ? Je n'ai rien trouvé qui précise cela mais c'est fréquent

**Comment by annepoirot** [comment]
Réponse de Météo France : 
Un index UV = 0 signifie bien que sa valeur est nulle. En gros, le soleil ne montrera pas le bout de son nez de toute la journée (un peu comme aujourd'hui en Alsace...). Une prévision absente (et pas une "mesure", attention !) est codée par une absence de valeur dans la colonne ou bien -999.

**Comment by fcoufour** [comment]
Merci pour les infos utiles @annepoirot. Est-ce qu'on aurait reçu une documentation technique, notamment pour ces cas particuliers ?
Précision intéressante : c'est une prévision, y compris pour la donnée du jour (J0).

**Comment by annepoirot** [comment]
Nous allons mettre en place un flux provisoire en mode expérimentation selon les modalités suivantes :
- flux ftp ou sftp vers un serveur de Recosanté (merci de m'indiquer un serveur de dépôt)
- un envoi par jour vers 5h du matin
- prévision IUV max quotidien pour toutes les communes de la France Métropolitaine et des OM
- prévisions pour J, J+1 et J+2
- fichier ASCII du type : id-commune;dateJ;valeurJ;valeurJ1;valeurJ2

**Comment by fcoufour** [comment]
Ci-dessous les recommandations en l'état pour l'indice UV 1 (recommandation la plus courte) avec et sans le bloc "enfants" :

![reco-indiceuv-1](https://user-images.githubusercontent.com/23194091/151974458-888a0fee-f927-4ea4-979f-ef1e9e707a7b.png)
![reco-indiceuv-1-enfants](https://user-images.githubusercontent.com/23194091/151974462-bd3567d8-5e05-4a01-8505-e267f5778609.png)

Idem dans le cas d'un indice UV égal à 8 (recommandation la plus longue) :

![reco-indiceuv-8](https://user-images.githubusercontent.com/23194091/151974494-303f25d0-3b3a-4e4f-98af-8285e64b352f.png)
![reco-indiceuv-8-enfants](https://user-images.githubusercontent.com/23194091/151974490-17f03e99-1485-4ae3-b554-46893d5543d8.png)

Il est possible de ne mettre le bloc "enfants" qu'à partir d'une certaine classe d'indice UV (par exemple lorsque supérieur ou égal à 3)

**Comment by MarinePurson** [comment]
A vrai dire, je trouve ça assez incohérent avec les autres tuiles de mettre la reco enfant...
Ou alors il faudrait simplifier : 
Indice UV
Risque faible
Pas de protection requise. Ne pas exposer les enfants de moins de un an et éviter l'exposition des enfants de moins de 10 ans.

**Comment by fcoufour** [comment]
C'est aussi mon avis 😄 , c'est pour cela que je tenais à faire l'essai visuel.

**Comment by annepoirot** [comment]
Il y a d'autres jeux de données (épisode de pollution, vigi météo, air) pour lesquels ont mentionne une phrase qui concerne une population particulière (enfants ou personnes sensibles). Du coup je pense que ce n'est pas complètement incohérent de faire ça pour l'indice UV. 
Par contre effectivement il faut qu'il y ait une cohérence dans la manière de l'amener sans la question "Vous avez des enfants". 

**Voilà ma proposition sur les recommandations @fcoufour :**
- On supprime les phrase "protection nécessaire" et "protection renforcée"
- Lorsqu'il y a plusieurs recommandations, on les affiches avec des bullet points (c'est ce qu'on fait pour la vigilance météo). 
- Pour le risque UV "faible" (1 et 2), je mettrais le soleil en gris pour être cohérent avec les autres icônes.
- J'enlèverais le bout de phrase "En complément de ces mesures" et mettrais directement "Appliquer une crème
de protection solaire au minimum d’indice SPF 30+ sur les zones découvertes"
- Pour les recommandations enfant je les ajouterais donc à la liste des recommandations envoyées à partir d'un indice UV 3  et je resterais sur une recommandation courte et simple : 
Ne pas exposer au soleil les enfants de moins de un an et éviter l'exposition des enfants jusqu'à 10 ans.
=> je vois avec Narimen sur ce sujet.

- @fcoufour les recommandations seront bien accessibles via : https://api.recosante.beta.gouv.fr/recommandations/ ? J'aimerais pouvoir les trouver avec le filtre "type" dans la barre de recherche. 

- Autre question sur l'affichage : est-ce qu'on veut mettre le numéro de l'indice UV entre parenthèse ? Je trouve que ça jure un peu avec le reste. Qu'en pensez vous @MarinePurson @fcoufour ?

**Comment by fcoufour** [comment]
> les recommandations seront bien accessibles via : https://api.recosante.beta.gouv.fr/recommandations/ ? J'aimerais pouvoir les trouver avec le filtre "type" dans la barre de recherche.

J'ai repris la même logique que pour les autres recommandations donc le back office permettra de sélectionner une classe d'indice UV basée sur l'échelle Météo France et de saisir la recommandation correspondante.

> Autre question sur l'affichage : est-ce qu'on veut mettre le numéro de l'indice UV entre parenthèse ? Je trouve que ça jure un peu avec le reste.

Météo France fait le choix de mettre la valeur de l'indice UV en avant et seulement lui. Si on se considère plus grand public, ce n'est pas illogique de faire plutôt figurer le risque. Je pense néanmoins que la valeur apporte une précision peut-être nécessaire. On pourrait néanmoins peut-être alléger en mettant : "Faible (UV 1)", "Modéré (UV 3)", "Fort (UV 6)", "Très fort (UV 8)", "Extrême (UV 11)". Qu'en pensez-vous ?

> Pour le risque UV "faible" (1 et 2), je mettrais le soleil en gris pour être cohérent avec les autres icônes.

J'ai repris strictement les couleurs de Météo France dont celle-ci. Il peut y avoir une valeur nulle ou absente qui se matérialise par l'icône en bleu gris (celle par défaut) avec un texte différent selon les cas. Est-ce OK pour toi ?

Comment souhaites-tu procéder pour les recommandations déjà pour une version immédiate sans recommandation "enfants" ? Préfères-tu me les transmettre via votre document consolidé ? (cela me permettrait de tester l'intégration)
Ou préfères-tu plutôt les saisir dans le back office après mise en ligne ?

**Comment by annepoirot** [comment]
[Recommandations dashboard UV_AP.docx](https://github.com/betagouv/recosante-api/files/7988011/Recommandations.dashboard.UV_AP.docx)
Partons sur ça pour le moment et je me charge des négociations à faire sur la partie enfant. On dit rien de faux dans ce qui est écrit donc je dis go :)

**Comment by annepoirot** [comment]
Lors du RDV avec MSS et SPF ya deux semaines on avait acté sur ça oui
<img width="1013" alt="Algorithme Recosanté Vigilance" src="https://user-images.githubusercontent.com/63290799/152192668-d029737d-5f02-4884-bd5f-d6c62752b8bb.png">

**Comment by MarinePurson** [comment]
Ok autant pour moi j'avais compris le contraire !

**Comment by fcoufour** [comment]
Très bien, merci @annepoirot et @MarinePurson. Je pars là-dessus, on modifiera via le back-office plus tard si nécessaire

**Comment by annepoirot** [comment]
Du coup après échanges, il semblerait qu'on ait encore quelques allez retour avec SPF sur le sujet enfants donc je dirais ajoutant sans la partie sur les enfants @fcoufour

**Comment by fcoufour** [comment]
C'est noté, tu rajouteras le bloc "enfants" via le back office une fois les textes validées avec MSS / SPF

**Comment by fcoufour** [comment]
Voici ce que ça donne en l'état : https://github.com/betagouv/recosante/issues/177#issuecomment-1028773091
