### ISSUE TITLE
Bug de données pour certaines villes en Occitanie

### ISSUE THREAD

**Issue by annepoirot** [betagouv/recosante-api#288]
Aucune donnée à montrer pour la ville de Roquemaure (30221) région: 'Occitanie'
Aucune donnée à montrer pour la ville de Saze (30315) région: 'Occitanie'
Aucune donnée à montrer pour la ville de Pujaut (30209) région: 'Occitanie'
Aucune donnée à montrer pour la ville de Roquemaure (30221) région: 'Occitanie'
Aucune donnée à montrer pour la ville de Saze (30315) région: 'Occitanie'
Aucune donnée à montrer pour la ville de Pujaut (30209) région: 'Occitanie'

**Comment by annepoirot** [comment]
Apparemment Occitanie n'envoie pas tous les EPCI 
@l-vincent-l regarde lesquels manquent et @annepoirot leur écrira

**Comment by annepoirot** [comment]
On va vérifier la liste des EPCI pour lesquels ATMO Occitanie envoie des données et voir si ça couvre toutes les données.  Si ya des manques, on enverra un mail

**Comment by l-vincent-l** [comment]
Voici la liste des villes pour lesquelles nous n’avons pas de données 
```
30209, Pujaut, Gard, 248400251, CA du Grand Avignon (COGA)
30217, Rochefort-du-Gard, Gard, 248400251, CA du Grand Avignon (COGA)
30011, Les Angles, Gard, 248400251, CA du Grand Avignon (COGA)
30221, Roquemaure, Gard, 248400251, CA du Grand Avignon (COGA)
30312, Sauveterre, Gard, 248400251, CA du Grand Avignon (COGA)
30315, Saze, Gard, 248400251, CA du Grand Avignon (COGA)
30351, Villeneuve-lès-Avignon, Gard, 248400251, CA du Grand Avignon (COGA)
32004, Arblade-le-Bas, Gers, 200030435, CC d'Aire-sur-l'Adour
32017, Aurensan, Gers, 200030435, CC d'Aire-sur-l'Adour
32027, Barcelonne-du-Gers, Gers, 200030435, CC d'Aire-sur-l'Adour
32046, Bernède, Gers, 200030435, CC d'Aire-sur-l'Adour
32108, Corneillan, Gers, 200030435, CC d'Aire-sur-l'Adour
32145, Gée-Rivière, Gers, 200030435, CC d'Aire-sur-l'Adour
32192, Lannux, Gers, 200030435, CC d'Aire-sur-l'Adour
32333, Projan, Gers, 200030435, CC d'Aire-sur-l'Adour
32424, Ségos, Gers, 200030435, CC d'Aire-sur-l'Adour
32460, Vergoignan, Gers, 200030435, CC d'Aire-sur-l'Adour
65018, Arbéost, Hautes-Pyrénées, 246401756, CC Pays de Nay
65176, Ferrières, Hautes-Pyrénées, 246401756, CC Pays de Nay
```
Les colonnes sont les suivantes : 
 * INSEE,
 * Nom de la commune
 * Nom du département
 * Code de l’EPCI
 * Nom de l’EPCI

**Comment by florianpanchout** [comment]
Ça refonctionne

**Comment by annepoirot** [comment]
Retour de Delphine que je mets ici au cas où pour plus tard : 
>Mon collègue d’Atmo Occitanie a ajouté les EPCI manquantes dont la commune centrale est bien en Occitanie. En effet, les communes que tu m’as transmises sont bien des communes d’Occitanie mais ne sont pas dans des EPCI qui sont en Occitanie ; elles n’ont jamais été mis en ligne. Les données ne sont donc pas accessibles seulement depuis quelques jours.
Il a donc ajouté les 3 EPCI supplémentaires (on arrive donc à 161 +3) qui couvrent les communes manquantes dont le point de représentation se trouve environ au niveau de la commune centrale de la partie de l’EPCI présente en Occitanie.
