### ISSUE TITLE
Ajouter les recommandations vigilance météo dans le catalogue

### ISSUE THREAD

**Issue by annepoirot** [betagouv/recosante-api#291]
- [x] ajouter une catégorie "vigilance météo" dans les filtres 
- [x] ajouter les filtres par niveau de vigilance "vigilance verte", "vigilance jaune", "vigilance orange" et "vigilance rouge"
- [x] ajouter les filtres type de vigilance "vent violent",  "vagues-submersion",  "pluie-inondation", "crues", "orages", "neige-verglas", "avalanches", "canicule" et "grand froid".
- [x] ajouter les recommandations une fois validées

Pour une recommandation données qui fait partie de la catégorie "vigilance météo", je dois pouvoir sélectionner le type de vigilance ET le niveau de vigilance.

**Comment by l-vincent-l** [comment]
@annepoirot Tu peux ajouter les recommandations
