### ISSUE TITLE
Bug de données auvergne rhone alpes

### ISSUE THREAD

**Issue by annepoirot** [betagouv/recosante-api#292]

**Comment by florianpanchout** [comment]
Front modifié pour que la page s'affiche sans les données ATMO. Mais je ne devrais pas recevoir ce format la de l'api (objet vide pour l'indice ATMO)

**Comment by l-vincent-l** [comment]
> Front modifié pour que la page s'affiche sans les données ATMO. Mais je ne devrais pas recevoir ce format la de l'api (objet vide pour l'indice ATMO)

Ce problème sera suivi dans cette issue https://github.com/betagouv/recosante-api/issues/293

**Comment by annepoirot** [comment]
Correction faite, on voit si c'est bon demain.

**Comment by l-vincent-l** [comment]
C’est bon \o/
