### ISSUE TITLE
Changer le flux de données de la Guyane

### ISSUE THREAD

**Issue by annepoirot** [betagouv/recosante-api#296]
https://dservices8.arcgis.com/5JImMrIjAqUJnR3H/arcgis/services/ind_guyane_nouvel_indice/WFSServer?service=wfs&request=getcapabilities

**Comment by fcoufour** [comment]
Pour l'indice ATMO : https://dservices8.arcgis.com/5JImMrIjAqUJnR3H/arcgis/services/ind_guyane_nouvel_indice/WFSServer?service=wfs&request=getfeature&typeName=ind_guyane_nouvel_indice:ind_guyane_agglo&outputFormat=GEOJSON

Pour les épisodes de pollution sur l'API : https://admindata.atmo-france.org/api/data/114/%7b%22code_zone%22:%7b%22operator%22:%22=%22,%22value%22:%22973%22%7d,%22date_ech%22:%7b%22operator%22:%22=%22,%22value%22:%222022-09-19%22%7d%7d?withGeom=false

@l-vincent-l  je t'ai mis les 2 flux ici
