### ISSUE TITLE
Bug données Auvergne Rhone Alpes

### ISSUE THREAD

**Issue by annepoirot** [betagouv/recosante-api#298]
Vincent utilise ce flux : https://data-atmoaura.opendata.arcgis.com/datasets/813d359d4e7e4705af45a6f28294cad9_0/explore?location=45.428977%2C4.621968%2C8.45&showTable=true

**Comment by l-vincent-l** [comment]
Il y a des données pour certaines villes, mais pas les plus grosses, par exemple il n’y a plus de données pour Lyon 

https://data-atmoaura.opendata.arcgis.com/datasets/813d359d4e7e4705af45a6f28294cad9_0/explore?filters=eyJjb2RlX3pvbmUiOlsiNjkxMjMiXX0%3D&location=45.402504%2C4.621968%2C8.00&showTable=true

Mais pas de souci il y a bien les données pour ambléon https://data-atmoaura.opendata.arcgis.com/datasets/813d359d4e7e4705af45a6f28294cad9_0/explore?filters=eyJkYXRlX2VjaCI6WyIyMDIxLTExLTE2VDAwOjAwOjAwWiJdfQ%3D%3D&location=45.402504%2C4.621968%2C8.00&showTable=true

**Comment by annepoirot** [comment]
Ca a été mis à jour non ?

**Comment by florianpanchout** [comment]
Pas de donnée pour Lyon aujourd'hui : https://recosante.beta.gouv.fr/place/69123/lyon/

**Comment by annepoirot** [comment]
Mail envoyé à Delphine
