### ISSUE TITLE
[outil csv] La région Occitanie ne fonctionne pas

### ISSUE THREAD

**Issue by annepoirot** [betagouv/recosante-api#30]
Colonnes région, lien AASQA et QA

**Comment by DavidBruant** [comment]
La même qu'avec l'IDF, l'API qu'on utilise fonctionne... l'après-midi...
...ce qui nous inutile pour notre usage

**Comment by DavidBruant** [comment]
Solution intérmédiaire : https://github.com/betagouv/ecosante/issues/31

**Comment by DavidBruant** [comment]
J'ai eu une info d'ATMO Occitanie que c'est corrigé de leur côté apparemment
Voyons demain si ça marche
