### ISSUE TITLE
Ajouter la licence sur les données

### ISSUE THREAD

**Issue by l-vincent-l** [betagouv/recosante-api#301]
Ajouter la licence sur les données

Pour chaque région aller chercher la licence des données

**Comment by l-vincent-l** [comment]
Il n’y a pas de licence pour ce jeu de données https://data-atmoaura.opendata.arcgis.com/datasets/813d359d4e7e4705af45a6f28294cad9_0/about (bon après y a plus de données non plus)

**Comment by annepoirot** [comment]
- Auvergne-Rhone-Alpes : il y a [cette page](https://data-atmoaura.opendata.arcgis.com/pages/conditions) non ? 
- Guadeloupe : c'est écrit sur la [page d'accueil](https://data-gwadair.opendata.arcgis.com/) que c'est ODbL
- IDF : c'est le jeu de données que tu utilise ? Il est marqué que la dernière actualisation date de avril 2021. Sinon c'est écrit aussi sur la [page d'accueil](https://data-airparif-asso.opendata.arcgis.com/).
- Normandie : lorsque je clique sur l'indice ATMO ils renvoient sur [ce lien ](https://api.atmonormandie.fr/index.php/lizmap/service/?repository=dindice&project=flux_indice_atmo_normandie&SERVICE=WFS&VERSION=1.3.0&REQUEST=GetCapabilities) qui donne la licence. 
- Sud : c'est dans [mentions légales](https://cigale.atmosud.org/contact.php)

**Comment by annepoirot** [comment]
- Martinique : https://data-madininair.opendata.arcgis.com/pages/licence-dutilisation

Décision avec Vincent de tout mettre en ODbL. Ajouter une mention dans la doc @l-vincent-l
