### ISSUE TITLE
Etre alerté lorsque l'envoi de la newsletter bug

### ISSUE THREAD

**Issue by annepoirot** [betagouv/recosante-api#304]
- Il faudrait avoir un système qui envoie un mail d'alerte lorsque la newsletter n'st pas partie pour n'importe quelle raison. 
- Et ensuite réfléchir à un process de debug, notamment pour les weekend. 
- Mettre des log pour être alerté lorsqu'on a un bug

**Comment by MarinePurson** [comment]
Parallèlement, je pense que l'utilisateur devrait recevoir un message automatique le renvoyant vers le site les jours où la newsletter et les notifs ne s'envoient pas.

Par exemple : https://chhedjg.r.bh.d.sendibt3.com/tr/mr/OePZYrEzCcbaOLgyZYOw3szC1Ksvp5Q4hiHPKFgjULi7XjbBVtm2opC2y3DloNF_rGKVqpJmyHz5-vOt-lb0E0iHx2BpFw6lbXIGGUtbLCMwNBxQHhJbgU3ZY0iaedFG8F-XXUzzxUNaJYq9FsCEROEkDPJRiQ
