### ISSUE TITLE
Lorsque l'indice ATMO bug, les notifications s'envoient en plusieurs fois

### ISSUE THREAD

**Issue by annepoirot** [betagouv/recosante-api#309]
Cas de Franck qui a reçu 10 notifications tous les jours depuis samedi alors que l'indice ATMO dans sa commune bug (Grandville).

Il semblerait que ce soit un bug du au fait que l'indice ATMO ne soit pas disponible, comme s'il y avait plusieurs tentatives d'envoi. 

De plus il semblerait qu'il y ait une différence de règle entre les mails et les notifs car le risque d'allergie nul est envoyé en notif, quand il n'est pas envoyé par mail.

**Comment by annepoirot** [comment]
Dans les notifications de Franck, il y avait quand même le risque nul. Donc il faudrait que la notification soit envoyée sur les mêmes règles que le mail, c'est à dire que s'il n'y a pas de données disponibles, alors on attend jusqu'à 14h pour envoyer la notification finale. 

Si à 14h les données ne sont tjrs pas disponibles, on envoie la notification quand même (une seule fois) avec une phrase type : 
- Indice de la qualité de l'air : pas de données disponibles
- Risque d'allergie aux pollens : pas de données disponibles

**Comment by l-vincent-l** [comment]
On est sur que ça arrive encore ?
J’arrive pas à reproduire le comportement.

**Comment by annepoirot** [comment]
Ps sur non, c'était il y a longtemps (1 mois)
