### ISSUE TITLE
Données RAEP indisponibles

### ISSUE THREAD

**Issue by florianpanchout** [betagouv/recosante-api#311]
Depuis hier (30/12) les données RAEP ne sont plus disponibles pour l'ensemble des communes : https://api.recosante.beta.gouv.fr/v1/?insee=68112&date=2021-12-30&show_raep=true

**Comment by fcoufour** [comment]
Merci @florianpanchout , vu aussi dans les rapports d'envoi des emails.

J'ai regardé rapidement à quoi c'est dû. En fait, le fichier CSV depuis lequel on récupère les données est daté du 23/12/2021 et a une durée de vie d'une semaine d'après le code ce qui nous amenait à hier (30/12).

Peut-être une opération manuelle hebdomadaire qui n'a pas pu être réalisée par le fournisseur en cette période ? Vous en savez sans doute plus que moi là-dessus, c'est déjà arrivé ?

**Comment by florianpanchout** [comment]
J'imaginais que la procédure était automatisée de leur côté, mais peut être que non. @annepoirot a le contact du rnsa

**Comment by fcoufour** [comment]
A voir avec Anne et Vincent d'où vient cette durée de validité d'une semaine et éventuellement reboucler avec le contact RNSA pour savoir si validité plus longue sur certaines périodes où il y a peu de variations des allergènes (ici cupressacées seulement).

En tout cas, leur site indique bien la même date de mise à jour (le 23/12) : https://www.pollens.fr/.

**Comment by annepoirot** [comment]
J'ai contacté le RNSA

**Comment by annepoirot** [comment]
Normalement un nouveau fichier CSV vient d'être ajouté, est-ce que ça devrait se mettre automatiquement à jour ou il y a quelque chose à faire côté back ? Je ne sais pas si tu as une idée @fcoufour ?

**Comment by fcoufour** [comment]
C'est automatique mais je ne sais pas quand c'est planifié je regarde. Merci !

**Comment by fcoufour** [comment]
C'est toutes les heures. Je confirme que le fichier est à jour sur le lien de livraison.

**Comment by florianpanchout** [comment]
Et ça s'affiche à nouveau en front 🎉

**Comment by fcoufour** [comment]
Tout à fait pour Paris, Marseille, Lyon et... Granville 😄. Par contre, les logs de la console Clever Cloud sont aux abonnés absents.

**Comment by fcoufour** [comment]
@annepoirot pour rétro, c'était un oubli de leur part et c'est manuel de leur côté ? J'ai vu qu'ils avaient aussi mis à jour leur site.
