### ISSUE TITLE
Fournir l'export pour Se loger

### ISSUE THREAD

**Issue by annepoirot** [betagouv/recosante-api#374]
- On a besoin de l'export pour les villes de plus de 100 000 habitants. 
- Sur l'ensemble des indices ATMO de juin 2021 à juin 2022. 

=> est-ce qu'on peut avoir un export même avant juin pour pouvoir le regarder et le bidouiller un peu ?

**Comment by l-vincent-l** [comment]
Bon bon j’ai passé du temps là dessus.
L’API d’ATMO ne pourrait pas beaucoup nous aider là dessus, ils n’ont pas la données pour toutes les régions au 01/01/2021.

On pourrait aller sur toutes les régions et prendre les relevés des données pour l’année passée.
Par contre c’est sur un an glissant ; ça commence donc au 20 avril (aujourd’hui).

**Comment by annepoirot** [comment]
- On essaye de passer par l'API ATMO, on filtre sur les grandes villes
- On identifie si il y a des trous dans la raquette
- Là où il y a des trous, on comble

**Comment by annepoirot** [comment]
Voir si on en parle à ATMO ou au BQA

**Comment by annepoirot** [comment]
[export_recosante.csv](https://github.com/betagouv/recosante-api/files/8698303/export_recosante.csv)
