### ISSUE TITLE
Bug QA en Nouvelle Aquitaine

### ISSUE THREAD

**Issue by annepoirot** [betagouv/recosante-api#399]
Pas de qualité de l’air pour la ville de Dax (40088) région: 'Nouvelle-Aquitaine'
Pas de qualité de l’air pour la ville de Grenade-sur-l'Adour (40117) région: 'Nouvelle-Aquitaine'
Pas de qualité de l’air pour la ville de Serres-Castet (64519) région: 'Nouvelle-Aquitaine'
Pas de qualité de l’air pour la ville de Grenade-sur-l'Adour (40117) région: 'Nouvelle-Aquitaine'
Pas de qualité de l’air pour la ville de Saint-Pierre (97416) région: 'La Réunion'
Pas de qualité de l’air pour la ville de Onesse-Laharie (40210) région: 'Nouvelle-Aquitaine'
Pas de qualité de l’air pour la ville de Soorts-Hossegor (40304) région: 'Nouvelle-Aquitaine'
Pas de qualité de l’air pour la ville de Dax (40088) région: 'Nouvelle-Aquitaine'
no_raep pour la ville de Fort-de-France (97209) région: 'Martinique'
Pas de qualité de l’air pour la ville de Vieux-Boucau-les-Bains (40328) région: 'Nouvelle-Aquitaine'
Pas de qualité de l’air pour la ville de Vieux-Boucau-les-Bains (40328) région: 'Nouvelle-Aquitaine'
Pas de qualité de l’air pour la ville de Navarrenx (64416) région: 'Nouvelle-Aquitaine'
Pas de qualité de l’air pour la ville de Dax (40088) région: 'Nouvelle-Aquitaine'
Pas de qualité de l’air pour la ville de Serres-Castet (64519) région: 'Nouvelle-Aquitaine'
no_raep pour la ville de Fort-de-France (97209) région: 'Martinique'
Pas de qualité de l’air pour la ville de Saubion (40291) région: 'Nouvelle-Aquitaine'
Pas de qualité de l’air pour la ville de Aubin (64073) région: 'Nouvelle-Aquitaine'

=> Peut-être du aux feux ? Est-ce que c'est parce que eux n'ont pas actualisé ? Car ça fonctionne pour d'autres communes du coin qui ont bien un indice ATMO "événement"

**Comment by l-vincent-l** [comment]
Ils ont du mettre un peu de temps à s’adapter, je n’ai effectivement rien pour hier dans la base de donnée, par contre aujourd’hui j’ai bien événement.
