### ISSUE TITLE
Modifier la page d'avis

### ISSUE THREAD

**Issue by annepoirot** [betagouv/recosante-api#82]
Organiser un atelier pour voir ce qu'on veut faire

**Comment by l-vincent-l** [comment]
J’ai fait un test pour voir ce que pourrait donner cette page
Je suis arrivé à ça 
![image](https://user-images.githubusercontent.com/2757318/108385427-f1b04580-720b-11eb-8846-19720507d52c.png)
je ne suis pas satisfait 
 * du design
 * de la quantité d‘information donnée
 * de la quantité d’information qu’on demande
 * de la formulation
Si on veut aller là dessus il faut retravailler ces points en amont.

Le travail est sur ma branche locale `demander_avis`

**Comment by florianpanchout** [comment]
@annepoirot  Qu'en est il de cette issue ?

**Comment by annepoirot** [comment]
Il faut qu'on se penche dessus pour voir ce qu'on veut en faire de cette page
